// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbixeezuaxiccexyinru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiaXhlZXp1YXhpY2NleHlpbnJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mjk5MzYsImV4cCI6MjA2NDUwNTkzNn0.rAHgXUu3ai-B7cCWymv6ENTBY6KxsahtEcAoi745ts4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);